# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push

jobs:
  local-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Contrast Local Scan
        uses: Contrast-Security-OSS/contrast-local-scan-action@v1.0.1
        with:
          apiUrl: "https://teamserver-harmony-dev.contsec.com/Contrast/api/sast"
          apiUserName: "patrick.mcdevitt@contrastsecurity.com"
          apiKey: "LfXlest12DW34r7Gt4wSj4c6YYkEUMqc"
          apiServiceKey: "WT7TDX0M4AE8MRL"
          apiOrgId: "74f4cd04-6ca9-4eb7-a7a7-78909c2101cc"
